// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scheduler.Models;

#nullable disable

namespace Scheduler.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    partial class SchedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scheduler.Models.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EndDay")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Absences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 2,
                            EndDay = 26,
                            Month = 1,
                            StartDay = 8,
                            Type = "GO",
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 4,
                            EndDay = 20,
                            Month = 1,
                            StartDay = 20,
                            Type = "VP",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 9,
                            EndDay = 12,
                            Month = 1,
                            StartDay = 8,
                            Type = "BO",
                            Year = 2024
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 9,
                            EndDay = 26,
                            Month = 1,
                            StartDay = 22,
                            Type = "GO",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("Scheduler.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MonthsEmployed")
                        .HasColumnType("int");

                    b.Property<string>("ReligiousHoliday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TeamRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamRoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "TestFname1",
                            LastName = "TestLname1",
                            MonthsEmployed = 99,
                            TeamId = 1,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "TestFname2",
                            LastName = "TestLname2",
                            MonthsEmployed = 97,
                            TeamId = 1,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "TestFname3",
                            LastName = "TestLname3",
                            MonthsEmployed = 93,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "TestFname4",
                            LastName = "TestLname4",
                            MonthsEmployed = 92,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "TestFname5",
                            LastName = "TestLname5",
                            MonthsEmployed = 88,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "TestFname6",
                            LastName = "TestLname6",
                            MonthsEmployed = 79,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "TestFname7",
                            LastName = "TestLname7",
                            MonthsEmployed = 64,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "TestFname8",
                            LastName = "TestLname8",
                            MonthsEmployed = 61,
                            TeamId = 1,
                            TeamRoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "TestFname9",
                            LastName = "TestLname9",
                            MonthsEmployed = 56,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "TestFname10",
                            LastName = "TestLname10",
                            MonthsEmployed = 47,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "TestFname11",
                            LastName = "TestLname11",
                            MonthsEmployed = 35,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "TestFname12",
                            LastName = "TestLname12",
                            MonthsEmployed = 32,
                            TeamId = 1,
                            TeamRoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "TestFname13",
                            LastName = "TestLname13",
                            MonthsEmployed = 28,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "TestFname14",
                            LastName = "TestLname14",
                            MonthsEmployed = 25,
                            TeamId = 1,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "TestFname15",
                            LastName = "TestLname15",
                            MonthsEmployed = 99,
                            TeamId = 2,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "TestFname16",
                            LastName = "TestLname16",
                            MonthsEmployed = 97,
                            TeamId = 2,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "TestFname17",
                            LastName = "TestLname17",
                            MonthsEmployed = 93,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "TestFname18",
                            LastName = "TestLname18",
                            MonthsEmployed = 92,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "TestFname19",
                            LastName = "TestLname19",
                            MonthsEmployed = 88,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "TestFname20",
                            LastName = "TestLname20",
                            MonthsEmployed = 79,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "TestFname21",
                            LastName = "TestLname21",
                            MonthsEmployed = 64,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "TestFname22",
                            LastName = "TestLname22",
                            MonthsEmployed = 61,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "TestFname23",
                            LastName = "TestLname23",
                            MonthsEmployed = 56,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "TestFname24",
                            LastName = "TestLname24",
                            MonthsEmployed = 47,
                            TeamId = 2,
                            TeamRoleId = 3
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "TestFname25",
                            LastName = "TestLname25",
                            MonthsEmployed = 35,
                            TeamId = 2,
                            TeamRoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "TestFname26",
                            LastName = "TestLname26",
                            MonthsEmployed = 32,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "TestFname27",
                            LastName = "TestLname27",
                            MonthsEmployed = 28,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "TestFname28",
                            LastName = "TestLname28",
                            MonthsEmployed = 25,
                            TeamId = 2,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "TestFname29",
                            LastName = "TestLname29",
                            MonthsEmployed = 99,
                            TeamId = 3,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "TestFname30",
                            LastName = "TestLname30",
                            MonthsEmployed = 97,
                            TeamId = 3,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "TestFname31",
                            LastName = "TestLname31",
                            MonthsEmployed = 93,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "TestFname32",
                            LastName = "TestLname32",
                            MonthsEmployed = 92,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "TestFname33",
                            LastName = "TestLname33",
                            MonthsEmployed = 88,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "TestFname34",
                            LastName = "TestLname34",
                            MonthsEmployed = 79,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "TestFname35",
                            LastName = "TestLname35",
                            MonthsEmployed = 64,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "TestFname36",
                            LastName = "TestLname36",
                            MonthsEmployed = 61,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "TestFname37",
                            LastName = "TestLname37",
                            MonthsEmployed = 56,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "TestFname38",
                            LastName = "TestLname38",
                            MonthsEmployed = 47,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "TestFname39",
                            LastName = "TestLname39",
                            MonthsEmployed = 35,
                            TeamId = 3,
                            TeamRoleId = 3
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "TestFname40",
                            LastName = "TestLname40",
                            MonthsEmployed = 32,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "TestFname41",
                            LastName = "TestLname41",
                            MonthsEmployed = 28,
                            TeamId = 3,
                            TeamRoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "TestFname42",
                            LastName = "TestLname42",
                            MonthsEmployed = 25,
                            TeamId = 3,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "TestFname43",
                            LastName = "TestLname43",
                            MonthsEmployed = 99,
                            TeamId = 4,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "TestFname44",
                            LastName = "TestLname44",
                            MonthsEmployed = 97,
                            TeamId = 4,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "TestFname45",
                            LastName = "TestLname45",
                            MonthsEmployed = 93,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "TestFname46",
                            LastName = "TestLname46",
                            MonthsEmployed = 92,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "TestFname47",
                            LastName = "TestLname47",
                            MonthsEmployed = 88,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "TestFname48",
                            LastName = "TestLname48",
                            MonthsEmployed = 79,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "TestFname49",
                            LastName = "TestLname49",
                            MonthsEmployed = 64,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "TestFname50",
                            LastName = "TestLname50",
                            MonthsEmployed = 61,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "TestFname51",
                            LastName = "TestLname51",
                            MonthsEmployed = 56,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "TestFname52",
                            LastName = "TestLname52",
                            MonthsEmployed = 47,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "TestFname53",
                            LastName = "TestLname53",
                            MonthsEmployed = 35,
                            TeamId = 4,
                            TeamRoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "TestFname54",
                            LastName = "TestLname54",
                            MonthsEmployed = 32,
                            TeamId = 4,
                            TeamRoleId = 3
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "TestFname55",
                            LastName = "TestLname55",
                            MonthsEmployed = 28,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "TestFname56",
                            LastName = "TestLname56",
                            MonthsEmployed = 25,
                            TeamId = 4,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "TestFname57",
                            LastName = "TestLname57",
                            MonthsEmployed = 99,
                            TeamId = 5,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "TestFname58",
                            LastName = "TestLname58",
                            MonthsEmployed = 97,
                            TeamId = 5,
                            TeamRoleId = 1
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "TestFname59",
                            LastName = "TestLname59",
                            MonthsEmployed = 93,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "TestFname60",
                            LastName = "TestLname60",
                            MonthsEmployed = 92,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "TestFname61",
                            LastName = "TestLname61",
                            MonthsEmployed = 88,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "TestFname62",
                            LastName = "TestLname62",
                            MonthsEmployed = 79,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "TestFname63",
                            LastName = "TestLname63",
                            MonthsEmployed = 64,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "TestFname64",
                            LastName = "TestLname64",
                            MonthsEmployed = 61,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "TestFname65",
                            LastName = "TestLname65",
                            MonthsEmployed = 56,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "TestFname66",
                            LastName = "TestLname66",
                            MonthsEmployed = 47,
                            TeamId = 5,
                            TeamRoleId = 3
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "TestFname67",
                            LastName = "TestLname67",
                            MonthsEmployed = 35,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "TestFname68",
                            LastName = "TestLname68",
                            MonthsEmployed = 32,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "TestFname69",
                            LastName = "TestLname69",
                            MonthsEmployed = 28,
                            TeamId = 5,
                            TeamRoleId = 2
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "TestFname70",
                            LastName = "TestLname70",
                            MonthsEmployed = 25,
                            TeamId = 5,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "TestFname71",
                            LastName = "TestLname71",
                            MonthsEmployed = 99,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "TestFname72",
                            LastName = "TestLname72",
                            MonthsEmployed = 97,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "TestFname73",
                            LastName = "TestLname73",
                            MonthsEmployed = 93,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "TestFname74",
                            LastName = "TestLname74",
                            MonthsEmployed = 92,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "TestFname75",
                            LastName = "TestLname75",
                            MonthsEmployed = 88,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "TestFname76",
                            LastName = "TestLname76",
                            MonthsEmployed = 79,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "TestFname77",
                            LastName = "TestLname77",
                            MonthsEmployed = 64,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "TestFname78",
                            LastName = "TestLname78",
                            MonthsEmployed = 61,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "TestFname79",
                            LastName = "TestLname79",
                            MonthsEmployed = 56,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "TestFname80",
                            LastName = "TestLname80",
                            MonthsEmployed = 47,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "TestFname81",
                            LastName = "TestLname81",
                            MonthsEmployed = 35,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "TestFname82",
                            LastName = "TestLname82",
                            MonthsEmployed = 32,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "TestFname83",
                            LastName = "TestLname83",
                            MonthsEmployed = 28,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "TestFname84",
                            LastName = "TestLname84",
                            MonthsEmployed = 25,
                            TeamId = 6,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "TestFname85",
                            LastName = "TestLname85",
                            MonthsEmployed = 99,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "TestFname86",
                            LastName = "TestLname86",
                            MonthsEmployed = 97,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "TestFname87",
                            LastName = "TestLname87",
                            MonthsEmployed = 93,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "TestFname88",
                            LastName = "TestLname88",
                            MonthsEmployed = 92,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "TestFname89",
                            LastName = "TestLname89",
                            MonthsEmployed = 88,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "TestFname90",
                            LastName = "TestLname90",
                            MonthsEmployed = 79,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "TestFname91",
                            LastName = "TestLname91",
                            MonthsEmployed = 64,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "TestFname92",
                            LastName = "TestLname92",
                            MonthsEmployed = 61,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "TestFname93",
                            LastName = "TestLname93",
                            MonthsEmployed = 56,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "TestFname94",
                            LastName = "TestLname94",
                            MonthsEmployed = 47,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "TestFname95",
                            LastName = "TestLname95",
                            MonthsEmployed = 35,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "TestFname96",
                            LastName = "TestLname96",
                            MonthsEmployed = 32,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "TestFname97",
                            LastName = "TestLname97",
                            MonthsEmployed = 28,
                            TeamId = 7,
                            TeamRoleId = 4
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "TestFname98",
                            LastName = "TestLname98",
                            MonthsEmployed = 25,
                            TeamId = 7,
                            TeamRoleId = 4
                        });
                });

            modelBuilder.Entity("Scheduler.Models.NationalHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("NationalHolidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nova Godina"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nova Godina"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bozic"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dan Drzavnosti"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dan Drzavnosti"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Praznik Rada"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Praznik Rada"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Veliki Petak"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Velika Subota"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Uskrs"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Uskrsnji ponedeljak"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dan primirja u I svetskom ratu"
                        });
                });

            modelBuilder.Entity("Scheduler.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Scheduler.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("CurrentStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NextMonthStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NextMonthStartsWithNight")
                        .HasColumnType("bit");

                    b.Property<string>("ShiftPattern")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentMonth = 1,
                            CurrentStartDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TeamBn",
                            NextMonthStartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextMonthStartsWithNight = false,
                            ShiftPattern = "DN3"
                        },
                        new
                        {
                            Id = 2,
                            CurrentMonth = 1,
                            CurrentStartDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TeamČa",
                            NextMonthStartDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextMonthStartsWithNight = false,
                            ShiftPattern = "DN3"
                        },
                        new
                        {
                            Id = 3,
                            CurrentMonth = 1,
                            CurrentStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Teamić",
                            NextMonthStartDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextMonthStartsWithNight = true,
                            ShiftPattern = "DN3"
                        },
                        new
                        {
                            Id = 4,
                            CurrentMonth = 1,
                            CurrentStartDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TeamRn",
                            NextMonthStartDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextMonthStartsWithNight = false,
                            ShiftPattern = "DN3"
                        },
                        new
                        {
                            Id = 5,
                            CurrentMonth = 1,
                            CurrentStartDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TeamŠi",
                            NextMonthStartDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextMonthStartsWithNight = false,
                            ShiftPattern = "DN3"
                        },
                        new
                        {
                            Id = 6,
                            CurrentMonth = 1,
                            CurrentStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TeamPr",
                            NextMonthStartDate = new DateTime(2021, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextMonthStartsWithNight = false,
                            ShiftPattern = "8"
                        },
                        new
                        {
                            Id = 7,
                            CurrentMonth = 1,
                            CurrentStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TeamBo",
                            NextMonthStartDate = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextMonthStartsWithNight = false,
                            ShiftPattern = "8"
                        });
                });

            modelBuilder.Entity("Scheduler.Models.TeamRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vođa smene",
                            Name = "VT"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Reanimaciona ambulanta",
                            Name = "RA"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Spoljna reanimacija",
                            Name = "SR"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tehničar na strani",
                            Name = "--"
                        });
                });

            modelBuilder.Entity("Scheduler.Models.Absence", b =>
                {
                    b.HasOne("Scheduler.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Scheduler.Models.Employee", b =>
                {
                    b.HasOne("Scheduler.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scheduler.Models.TeamRole", "TeamRole")
                        .WithMany()
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("TeamRole");
                });

            modelBuilder.Entity("Scheduler.Models.Shift", b =>
                {
                    b.HasOne("Scheduler.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
